/* TABLES SANS DEPENDANCES */

/* CREATION TABLE ORGA */
CREATE TABLE ORGA
(
    idOrga INT(6) AUTO_INCREMENT,
    first_name VARCHAR(64) NOT NULL,
    last_name VARCHAR(64) NOT NULL,
    mail VARCHAR(256) NOT NULL,
    
    CONSTRAINT PK_ORGA PRIMARY KEY (idOrga)
);

/* CREATION TABLE SHIFT */
CREATE TABLE SHIFT
(
    idShift INT(6) AUTO_INCREMENT,
    start_date DATETIME NOT NULL,
    end_date DATETIME NOT NULL,
    
    CONSTRAINT PK_SHIFT PRIMARY KEY (idShift)    
);

/* TABLES AVEC DEPENDANCES */

/* CREATION TABLE PWD */
CREATE TABLE PWD
(
  idOrga INT(6) PRIMARY KEY,
  pwd VARCHAR(60),

  CONSTRAINT FK_PWD_IDORGA FOREIGN KEY (idOrga) REFERENCES ORGA(idOrga) ON DELETE CASCADE
);

/* CREATION TABLE TOKEN */
CREATE TABLE TOKEN
(
  idOrga INT(6) PRIMARY KEY UNIQUE,
  token VARCHAR(96),

  CONSTRAINT FK_TOKEN_IDORGA FOREIGN KEY (idOrga) REFERENCES ORGA(idOrga) ON DELETE CASCADE
);

/* CREATION TABLE TASK */
CREATE TABLE TASK
(
    idTask INT(6) AUTO_INCREMENT,
    name VARCHAR(64) NOT NULL,
    description VARCHAR(300) NOT NULL,
    idOrga INT(6) NOT NULL,
    
    CONSTRAINT PK_TASK PRIMARY KEY (idTask),
    CONSTRAINT FK_TASK_IDORGA FOREIGN KEY (idOrga) REFERENCES ORGA(idOrga)
);

/* CREATION TABLE SUBSHIFT */
CREATE TABLE SUBSHIFT
(
    idSubShift INT(6) AUTO_INCREMENT,
    start_date DATETIME,
    end_date DATETIME,
    idShift INT(6),
    
    CONSTRAINT PK_SUBSHIFT PRIMARY KEY (idSubShift),
    CONSTRAINT FK_SUBSHIFT FOREIGN KEY (idShift) REFERENCES SHIFT(idShift) ON DELETE CASCADE
);

/* CREATION TABLE SHIFT_ORGA */
CREATE TABLE SHIFT_ORGA
(
    idShift INT(6),
    idOrga INT(6),
    
    CONSTRAINT PK_SHIFT_ORGA PRIMARY KEY (idShift, idOrga),
    CONSTRAINT FK_SHIFT_ORGA_IDSHIFT FOREIGN KEY (idShift) REFERENCES SHIFT(idShift) ON DELETE CASCADE,
    CONSTRAINT FK_SHIFT_ORGA_IDORGA FOREIGN KEY (idOrga) REFERENCES ORGA(idOrga) ON DELETE CASCADE
);

/* CREATION TABLE SHIFT_TASK */
CREATE TABLE SHIFT_TASK
(
    idSubShift INT(6),
    idTask INT(6),
    
    CONSTRAINT PK_SHIFT_TASK PRIMARY KEY (idSubShift, idTask),
    CONSTRAINT FK_SHIFT_TASK_IDSUBSHIFT FOREIGN KEY (idSubShift) REFERENCES SUBSHIFT(idSubShift) ON DELETE CASCADE,
    CONSTRAINT FK_SHIFT_TASK_IDTASK FOREIGN KEY (idTask) REFERENCES TASK(idTask) ON DELETE CASCADE
);

/* CREATION TABLE TASK_ORGA */
CREATE TABLE TASK_ORGA
(
  idOrga INT(6),
  idTask INT(6),

  CONSTRAINT PK_TASK_ORGA PRIMARY KEY (idOrga, idTask),
  CONSTRAINT FK_TASK_ORGA_IDORGA FOREIGN KEY (idOrga) REFERENCES ORGA(idOrga) ON DELETE CASCADE,
  CONSTRAINT FK_TASK_ORGA_IDTASK FOREIGN KEY (idTask) REFERENCES TASK(idTask) ON DELETE CASCADE
);